baseURL = "https://outis42.com/"
languageCode = "zh-cn"
title = "outis42 | The Cognitive Mirror"
theme = "PaperMod"

[params.profileMode]
  enabled = false
  title = "outis42"
  subtitle = "探索 AI 如何重塑我们的思考、决策与自我认知。"
  imageUrl = "/images/avatar.jpg"
  imageWidth = 120
  imageHeight = 120